import { NextRequest, NextResponse } from 'next/server';
import { permissionErrorResponse, requireModulePermission } from '@/lib/auth/require-permission';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { apiFailure, apiSuccess, createRequestId, databaseErrorToHttp } from '@/lib/api/responses';

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function isValidOptionalDate(value: unknown) {
  if (value === null || value === undefined || value === '') return true;
  return typeof value === 'string' && Number.isFinite(new Date(value).getTime());
}

function nullableTrim(value: unknown) {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return trimmed ? trimmed : null;
}

function validateRegistration(body: Record<string, unknown>) {
  const fieldErrors: Record<string, string[]> = {};
  const idempotencyKey = nullableTrim(body.idempotency_key ?? body.idempotencyKey);

  if (!idempotencyKey || !UUID_PATTERN.test(idempotencyKey)) {
    fieldErrors.idempotency_key = ['A valid idempotency key is required.'];
  }

  for (const field of ['returnable_date', 'first_hearing_date', 'proceeding_filed_date', 'documents_served_date']) {
    if (!isValidOptionalDate(body[field])) {
      fieldErrors[field] = ['Invalid date.'];
    }
  }

  const assignedOfficerId = nullableTrim(body.assigned_officer_id ?? body.dlpp_action_officer_id);
  if (assignedOfficerId && !UUID_PATTERN.test(assignedOfficerId)) {
    fieldErrors.assigned_officer_id = ['Assigned officer must be a valid user ID.'];
  }

  if (body.case_number !== undefined && nullableTrim(body.case_number)) {
    fieldErrors.case_number = ['Case numbers are generated by the database and cannot be supplied by the browser.'];
  }

  return {
    idempotencyKey,
    fieldErrors,
    registration: {
      title: nullableTrim(body.title),
      description: nullableTrim(body.description),
      priority: nullableTrim(body.priority) ?? 'medium',
      region: nullableTrim(body.region),
      court_file_number: nullableTrim(body.court_file_number),
      track_number: nullableTrim(body.track_number),
      parties_description: nullableTrim(body.parties_description),
      opposing_party_name: nullableTrim(body.opposing_party_name),
      proceeding_filed_date: nullableTrim(body.proceeding_filed_date),
      documents_served_date: nullableTrim(body.documents_served_date),
      court_documents_type: nullableTrim(body.court_documents_type),
      matter_type: nullableTrim(body.matter_type),
      case_type: nullableTrim(body.case_type),
      returnable_date: nullableTrim(body.returnable_date),
      first_hearing_date: nullableTrim(body.first_hearing_date),
      returnable_type: nullableTrim(body.returnable_type),
      land_description: nullableTrim(body.land_description),
      zoning: nullableTrim(body.zoning),
      survey_plan_no: nullableTrim(body.survey_plan_no),
      lease_type: nullableTrim(body.lease_type),
      lease_commencement_date: nullableTrim(body.lease_commencement_date),
      lease_expiration_date: nullableTrim(body.lease_expiration_date),
      division_responsible: nullableTrim(body.division_responsible),
      allegations: nullableTrim(body.allegations),
      reliefs_sought: nullableTrim(body.reliefs_sought),
      opposing_lawyer_name: nullableTrim(body.opposing_lawyer_name),
      sol_gen_officer: nullableTrim(body.sol_gen_officer),
      assigned_officer_id: assignedOfficerId,
      officer_assigned_date: nullableTrim(body.officer_assigned_date),
      assignment_notes: nullableTrim(body.assignment_footnote ?? body.assignment_notes),
      dlpp_role: nullableTrim(body.dlpp_role) ?? 'defendant',
      section5_notice: body.section5_notice === true,
    },
  };
}

export async function POST(request: NextRequest) {
  const requestId = createRequestId();

  try {
    await requireModulePermission('cases', 'create');

    const body = await request.json().catch(() => null);
    if (!body || typeof body !== 'object' || Array.isArray(body)) {
      return NextResponse.json(apiFailure('INVALID_JSON', 'Request body must be valid JSON.', requestId), { status: 400 });
    }

    const { idempotencyKey, fieldErrors, registration } = validateRegistration(body as Record<string, unknown>);
    if (Object.keys(fieldErrors).length > 0 || !idempotencyKey) {
      return NextResponse.json(
        apiFailure('VALIDATION_FAILED', 'Please correct the highlighted fields.', requestId, fieldErrors),
        { status: 400 },
      );
    }

    const supabase = await createSupabaseServerClient();
    const { data, error } = await supabase.rpc('register_case' as never, {
      p_registration: registration,
      p_idempotency_key: idempotencyKey,
    } as never);

    if (error) throw error;

    return NextResponse.json(apiSuccess(data), { status: 201 });
  } catch (error) {
    const response = permissionErrorResponse(error);
    if (response) return response;

    console.error('Case registration failed', { requestId });
    const mapped = databaseErrorToHttp(error);
    return NextResponse.json(apiFailure(mapped.code, mapped.message, requestId), { status: mapped.status });
  }
}
